# Generated by Django 4.2.7 on 2023-12-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendorPerformanceAverages',
            new_name='VendorPerformanceAverage',
        ),
    ]
