# Generated by Django 4.2.7 on 2023-12-17 12:40

import Vendors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0002_rename_vendorperformanceaverages_vendorperformanceaverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, default=Vendors.models.generate_po_code, editable=False, max_length=100),
        ),
    ]
