# Generated by Django 4.2.7 on 2023-12-06 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Vendors', '0003_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
