# Generated by Django 4.2.7 on 2023-12-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0004_vendor_vendor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_user',
            new_name='vendor_user_id',
        ),
    ]
