# Generated by Django 4.2.7 on 2023-12-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0005_remove_purchaseorder_quality_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, choices=[('acknowledged', 'Acknowledged'), ('shipping', 'Shipping'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
