# Generated by Django 4.2.7 on 2023-12-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0006_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='acknowledgment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
